- name: Evaluate Namespace {{ pipeline_project }}
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    api_version: v1
    kind: Namespace
    name: '{{ pipeline_project }}'
    state: present

- name: Evaluate Tekton Required Files
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: '{{ verify_tls }}'
    state: present
    namespace: '{{ pipeline_project }}'
    resource_definition: "{{ lookup('file', item) }}"
  loop:
    - maven-local-pvc.yml
    - maven-task.yml
    - source-pvc.yml
