- name: Evaluate Namespace {{ pipeline_project }}
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    api_version: v1
    kind: Namespace
    name: '{{ pipeline_project }}'
    state: present

- name: Evaluate Tekton PVCs
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: '{{ verify_tls }}'
    state: present
    namespace: '{{ pipeline_project }}'
    resource_definition: "{{ lookup('file', item) }}"
  loop:
    - maven-local-pvc.yml
    - source-pvc.yml

- name: Evaluate Tekton Tasks
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: '{{ verify_tls }}'
    state: present
    namespace: '{{ pipeline_project }}'
    resource_definition: "{{ lookup('file', 'maven-task.yml') }}"
  register: crd_result
  retries: 220
  delay: 10
