apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgresqldb
    app.kubernetes.io/component: postgresqldb
    app.kubernetes.io/instance: postgresqldb
  name: postgresqldb
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: postgresqldb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: postgresqldb
    spec:
      containers:
      - env:
        - name: POSTGRESQL_ADMIN_PASSWORD
          value: redhat
        - name: POSTGRESQL_DATABASE
          value: camel
        - name: POSTGRESQL_PASSWORD
          value: redhat
        - name: POSTGRESQL_USER
          value: redhat
        image: quay.io/gcamposo/camel-demo-postgresql:latest
        imagePullPolicy: IfNotPresent
        name: postgresqldb
        ports:
        - containerPort: 5432
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
