apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresqldb
    app.kubernetes.io/component: postgresqldb
    app.kubernetes.io/instance: postgresqldb
  name: postgresqldb
spec:
  ports:
  - name: 5432-tcp
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    deployment: postgresqldb
  sessionAffinity: None
  type: ClusterIP

