- name: Evaluate Namespace {{ amq_project }}
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    api_version: v1
    kind: Namespace
    name: '{{ amq_project }}'
    state: present

- name: Evaluate Namespace Operator Group
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: '{{ verify_tls }}'
    state: present
    kind: OperatorGroup
    api_version: operators.coreos.com/v1
    namespace: '{{ amq_project }}'
    definition:
      metadata:
        name: '{{ amq_project }}-operator-group'
      spec:
        targetNamespaces:
          - '{{ amq_project }}'

- name: Evaluate AMQ Operator
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: '{{ verify_tls }}'
    state: present
    kind: Subscription
    api_version: operators.coreos.com/v1alpha1
    definition:
      metadata:
        name: amq-broker-rhel8
        namespace: '{{ amq_project }}'
      spec:
        channel: 7.12.x
        installPlanApproval: Automatic
        name: amq-broker-rhel8
        source: redhat-operators
        sourceNamespace: openshift-marketplace

- name: Wait for AMQ operator to install
  kubernetes.core.k8s_info:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: '{{ verify_tls }}'
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: activemqartemises.broker.amq.io
  register: _crd
  until: _crd.resources | list | length == 1
  retries: 10
  delay: 30
