---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: timer-to-db
spec:
  podMetricsEndpoints:
    - bearerTokenSecret:
        key: ''
      path: /q/metrics
      port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: timer-to-db
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: broker-to-s3
spec:
  podMetricsEndpoints:
    - bearerTokenSecret:
        key: ''
      path: /q/metrics
      port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: broker-to-s3
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: timer-to-s3
spec:
  podMetricsEndpoints:
    - bearerTokenSecret:
        key: ''
      path: /q/metrics
      port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: timer-to-s3      