- name: Install Trusted Application Pipeline
  hosts: localhost
  vars:
    delete_demo: false
    verify_tls: false
    insecure_skip_tls_verify: true
    camel_project: camel-dev
    hawtio_project: '{{ camel_project }}'

    # Minio configuration
    minio_stateful: true
    minio_project: '{{ tpa_project }}'
    minio_key: minio
    minio_secret: minio123
    minio_region: eu-west-1

    gitops_project: camel-dev

    # pipeline
    pipeline_project: demo-tap-pipeline

    # Devspaces Configuration
    devspaces_enabled: true

  tasks:
    - name: Check Required Parameters
      ansible.builtin.fail:
        msg: "This play requires 'server' and 'token' to be defined"
      when:
        - (server is not defined) or (token is not defined) or (server is none) or (token is none)
      ignore_errors: false

    - name: Set domain
      ansible.builtin.set_fact:
        domain: "{{ server | regex_replace('https://api.') | regex_replace(':6443') }}"

    - name: Set Subdomain
      ansible.builtin.set_fact:
        route_subdomain: "apps.{{ domain }}"

    - name: Include Tekton
      ansible.builtin.include_role:
        name: tekton

    - name: Include ArgoCD
      ansible.builtin.include_role:
        name: argocd

    - name: Include DevSpaces
      ansible.builtin.include_role:
        name: devspaces
      when: devspaces_enabled | bool

    - name: Include HawtIO
      ansible.builtin.include_role:
        name: hawtio
