- name: Evaluate ArgoCD Projects
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    state: present
    namespace: openshift-gitops
    resource_definition: "{{ lookup('template', item) }}"
  loop:
    - camel-argo-project.yml.j2

- name: Evaluate ArgoCD Applications
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    state: present
    resource_definition: "{{ lookup('template', item) }}"
  loop:
    - camel-application.yml.j2
